baseURL = "http://agenda.romnorkrets.no/"
DefaultContentLanguage = "no"
languageCode = "nb-no"
title = "Agenda 2021"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "infoside om Agenda 2021 i Romsdal og Nordmøre krets"
  logo = "img/agenda_logo.png" # Expecting square dimensions
  favicon = "img/agenda_logo.svg"
  dateFormat = "2. January, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[[menu.main]]
    name = "Info"
    url = ""
    weight = 1