baseURL = "https://agenda.romnorkrets.no/"
defaultContentLanguage = "no"
languageCode = "nb-no"
title = "Agenda 2021"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pluralizelisttitles = false

[Params]
  subtitle = "infoside om Agenda 2021 i Romsdal og Nordmøre krets"
  mainSections = ["info","nyheter"]
  logo = "img/agenda_logo.png" # Expecting square dimensions
  favicon = "img/agenda_logo.svg"
  dateFormat = "2. January, 2006"
  commit = "https://github.com/Sinhk/romnor-agenda2021/tree/"
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[[menu.main]]
    name = "Info"
    url = ""
    weight = 1

[[menu.main]]
    name = "Nyheter"
    url = "nyheter/"
    weight = 2

[[menu.main]]
    name = "Bilder"
    url = "side/bilder/"
    weight = 3

[[menu.main]]
    name = "Korona-screening"
    url = "side/korona-screening/"
    weight = 4

[languages]
  [languages.no]
    title = "Agenda 2021"
    weight = 1
